CHAT:
  welcome_msg: Hi! I'm your apartment assistant. I can help you book an apartment. Would you like me to start by listing our options?
  fallback_msg: The request is beyond my scope. I must explain that the system is developed only for assistance with booking an apartment or assistance with said apartment. I MUST NOT add any other kind of explanation.
PreNLU:
  system_prompt_file: prompts/gpt_prompts/pre_nlu_prompt.txt
  model_name: llama3
NLU:
  system_prompt_file: prompts/gpt_prompts/nlu_prompt.txt
  model_name: llama3
DM:
  system_prompt_file: prompts/gpt_prompts/dm_prompt.txt
  model_name: llama3
NLG:
  system_prompt_file: prompts/gpt_prompts/nlg_prompt.txt
  model_name: llama3
logger: chat_logger
