CHAT:
  welcome_msg: I am your calendar manager assistant, what can I help you with?

PreNLU:
  system_prompt_file: prompts/pre_nlu_prompt.txt
  model_name: llama3
NLU:
  system_prompt_file: prompts/nlu_prompt.txt
  model_name: llama3
DM:
  system_prompt_file: prompts/dm_prompt.txt
  model_name: llama3
NLG:
  system_prompt_file: prompts/nlg_prompt.txt
  model_name: llama3